import Head from 'next/head';
import { BiUserPlus } from 'react-icons/bi';
import ClientList from '../components/ClientList';
import ClientForm from '../components/ClientForm';
import { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { toggleChangeAction } from '../redux/reducer';

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  return (
    <div>
      <Head>
        <title>Client Management</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='py-10'>
        <h1 className='text-xl md:text-5xl text-center font-bold py-10'>
          Client Management
        </h1>
        <div className='container mx-auto flex justify-between py-5 border-b'>
          <div className='left flex gap-3'>
            <button
              onClick={handler}
              className='flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800'
            >
              Add Client{' '}
              <span className='px-1'>
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
        </div>
        {/*AddClient Form*/}

        {visible ? <ClientForm /> : <></>}

        {/*ClientList Table*/}
        <div className='container mx-auto'>
          <ClientList />
        </div>
      </main>
    </div>
  );
}
